export const productsData = [
  {
    id: 'metal-nfc-card',
    name_en: "Metal Magnetic NFC Card",
    name_ar: "بطاقة تعارف ممغنطة معدني - نضع تصميمك",
    description_en: "Premium metal NFC card with custom design",
    description_ar: "بطاقة معدنية فاخرة مع تصميمك الخاص",
    price: 130,
    original_price: null,
    discount_percentage: 0,
    image_url: "https://rawaj.click/wp-content/uploads/2024/12/Frame_44_1b99c720-5d9b-492e-b5fa-ea176d50a2ad-450x450.webp",
    category: "business_cards",
    is_customizable: true,
    features_en: ['Metal material', 'Magnetic', 'Custom design', 'Premium finish'],
    features_ar: ['مادة معدنية', 'مغناطيسي', 'تصميم مخصص', 'لمسة نهائية فاخرة']
  },
  {
    id: 'wooden-nfc-card',
    name_en: "Wooden NFC Business Card",
    name_ar: "بطاقة تعارف إلكتروني للمشاركة السريعة NFC - خشبي (تصميم مخصص)",
    description_en: "Elegant wooden NFC business card with custom design",
    description_ar: "بطاقة خشبية أنيقة بتصميم مخصص",
    price: 100,
    original_price: null,
    discount_percentage: 0,
    image_url: "https://rawaj.click/wp-content/uploads/2024/10/%D8%B9%D9%85%D8%A7%D8%AF-%D8%B1%D8%AF%D9%85%D8%A7%D9%86-3-450x450.png",
    category: "business_cards",
    is_customizable: true,
    features_en: ['Natural wood', 'Laser engraving', 'Eco-friendly', 'Custom design'],
    features_ar: ['خشب طبيعي', 'حفر بالليزر', 'صديق للبيئة', 'تصميم مخصص']
  },
  {
    id: 'magnetic-nfc-card',
    name_en: "Magnetic NFC Business Card",
    name_ar: "بطاقة تعارف ممغنطة NFC (تصميم مخصص)",
    description_en: "Premium plastic NFC card with magnetic feature",
    description_ar: "بطاقة بلاستيكية فاخرة مع ميزة مغناطيسية",
    price: 50,
    original_price: null,
    discount_percentage: 0,
    image_url: "https://rawaj.click/wp-content/uploads/2024/10/6-450x450.png",
    category: "business_cards",
    is_customizable: true,
    features_en: ['Magnetic back', 'Custom design', 'Premium plastic', 'Quick sharing'],
    features_ar: ['ظهر مغناطيسي', 'تصميم مخصص', 'بلاستيك فاخر', 'مشاركة سريعة']
  },
  {
    id: 'google-review-card',
    name_en: "Google Review NFC Card",
    name_ar: "بطاقة قيمنا على جوجل - NFC",
    description_en: "Collect Google reviews effortlessly",
    description_ar: "اجمع تقييمات جوجل بسهولة",
    price: 35,
    original_price: 60,
    discount_percentage: 42,
    image_url: "https://rawaj.click/wp-content/uploads/2024/12/Google-NFC-Instagam-Facebook-WhatsApp-Youtube-Snapchat-Android-iPhone-450x450.webp",
    category: "business_cards",
    is_customizable: true,
    features_en: ['Direct to Google', 'Instant reviews', 'Professional look', 'Easy to use'],
    features_ar: ['مباشرة لجوجل', 'تقييمات فورية', 'مظهر احترافي', 'سهل الاستخدام']
  },
  {
    id: 'review-keychain',
    name_en: "NFC Review Keychain",
    name_ar: "تعليقة مفاتيح NFC لزيادة مراجعات",
    description_en: "Portable NFC keychain for collecting reviews",
    description_ar: "تعليقة مفاتيح محمولة لجمع التقييمات",
    price: 45,
    original_price: 75,
    discount_percentage: 40,
    image_url: "https://rawaj.click/wp-content/uploads/2024/12/NFC-Epoxy-Keychain-NFC-Google-450x450.webp",
    category: "keychains",
    is_customizable: true,
    features_en: ['Compact design', 'Durable', 'Multiple colors', 'Review collection'],
    features_ar: ['تصميم مدمج', 'متين', 'ألوان متعددة', 'جمع التقييمات']
  },
  {
    id: 'social-keychain',
    name_en: "Social Media NFC Keychain",
    name_ar: "تعليقة مفاتيح وسائل التواصل (NFC)",
    description_en: "Share social media profiles instantly",
    description_ar: "شارك حساباتك على وسائل التواصل فوراً",
    price: 35,
    original_price: null,
    discount_percentage: 0,
    image_url: "https://rawaj.click/wp-content/uploads/2024/12/Instagram-NFC-Epoxy-Tag-NFC-Key-Card-13-56MHz-URL-Link-450x450.webp",
    category: "keychains",
    is_customizable: true,
    features_en: ['All platforms', 'Instant connect', 'Stylish design', 'Multiple options'],
    features_ar: ['جميع المنصات', 'اتصال فوري', 'تصميم أنيق', 'خيارات متعددة']
  },
  {
    id: 'premium-table-stand',
    name_en: "Premium Google Review Table Stand - NFC",
    name_ar: "ستاند طاولة فخامة لطلب التقييم على جوجل - NFC",
    description_en: "Elegant table stand for collecting reviews",
    description_ar: "ستاند طاولة أنيق لجمع التقييمات",
    price: 120,
    original_price: null,
    discount_percentage: 0,
    image_url: "https://rawaj.click/wp-content/uploads/2024/12/unnamed-file-12-450x450.webp",
    category: "stands",
    is_customizable: false,
    features_en: ['Premium acrylic', 'Desk stand', 'Professional look', 'Easy placement'],
    features_ar: ['أكريليك فاخر', 'حامل مكتب', 'مظهر احترافي', 'وضع سهل']
  },
  {
    id: 'quick-share-stand',
    name_en: "Quick Share Table Stand",
    name_ar: "ستاند طاولة للمشاركة السريعة (معلومات التواصل الاجتماعي ، منيو ، الموقع ..)",
    description_en: "Share contacts, menu, location instantly",
    description_ar: "شارك جهات الاتصال والمنيو والموقع فوراً",
    price: 129,
    original_price: 159,
    discount_percentage: 19,
    image_url: "https://rawaj.click/wp-content/uploads/2024/10/InstagramStandwhite_1800x1800-450x450.webp",
    category: "stands",
    is_customizable: true,
    features_en: ['Multi-purpose', 'Acrylic stand', 'Custom info', 'Restaurant ready'],
    features_ar: ['متعدد الأغراض', 'حامل أكريليك', 'معلومات مخصصة', 'جاهز للمطاعم']
  }
];

export const productCategories = [
  { value: 'all', label_en: 'All Products', label_ar: 'جميع المنتجات', icon: '🛍️' },
  { value: 'business_cards', label_en: 'Business Cards', label_ar: 'بطاقات الأعمال', icon: '📱' },
  { value: 'keychains', label_en: 'Keychains', label_ar: 'تعليقات المفاتيح', icon: '🔑' },
  { value: 'stands', label_en: 'Table Stands', label_ar: 'ستاندات الطاولة', icon: '📊' }
];